<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import type { Student, Guardian, Program, Content } from '$lib/types';
  let students: Student[] = []; let portalStudents: { isActive: boolean }[] = []; let guardians: Guardian[] = []; let programs: Program[] = []; let announcements: Content[] = []; let error = ''; let loading = true;
  onMount(async () => { try { [students, portalStudents, guardians, programs, announcements] = await Promise.all([api<Student[]>('/api/students'), api<{ isActive: boolean }[]>('/api/portal-admin/students'), api<Guardian[]>('/api/guardians'), api<Program[]>('/api/programs'), api<Content[]>('/api/announcements')]); } catch (e) { error = e instanceof Error ? e.message : 'Could not load dashboard.'; } finally { loading = false; } });
</script>
<svelte:head><title>Staff dashboard | TASK Karate</title></svelte:head>
<div class="toolbar"><div><span class="eyebrow">TODAY</span><h2>Good work starts with a clear desk.</h2><p class="muted">A quick operational view of the records this staff account can manage.</p></div></div>
{#if error}<div class="error" role="alert">{error}</div>{/if}{#if loading}<section class="card loading-card"><p class="muted">Loading operational counts…</p></section>{:else}<div class="metric-grid"><section class="card metric"><strong>{portalStudents.filter((student) => student.isActive).length}</strong><span>Portal students</span><small>Student hub database</small></section><section class="card metric"><strong>{students.length}</strong><span>Operations students</span><small>EF staff database</small></section><section class="card metric"><strong>{guardians.length}</strong><span>Active guardians</span></section><section class="card metric"><strong>{programs.length}</strong><span>Programs</span></section><section class="card metric"><strong>{announcements.filter((item) => item.status === 'Published').length}</strong><span>Published announcements</span></section></div><section class="card"><span class="eyebrow">WORKFLOWS</span><h2>What needs attention?</h2><div class="schedule-grid"><a class="schedule-item" href="/staff/students"><b>Manage students</b><small>Create, edit, view, or safely deactivate staff records.</small></a><a class="schedule-item" href="/staff/awards"><b>Manage recognition</b><small>Award Gold Stars and recalculate automatic milestones.</small></a><a class="schedule-item" href="/staff/classes"><b>Prepare class sessions</b><small>Choose a date and create the occurrences students can attend.</small></a><a class="schedule-item" href="/staff/helpers"><b>Plan helper coverage</b><small>Volunteer for upcoming sessions and see who is helping each class.</small></a><a class="schedule-item" href="/staff/attendance"><b>Check attendance</b><small>Record a student once per session and review the roster.</small></a><a class="schedule-item" href="/staff/announcements"><b>Publish an announcement</b><small>Drafts stay private until staff explicitly publishes them.</small></a></div></section>{/if}
