<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  type Leaderboard = { period: string; periodLabel: string; entries: { rank: number; studentId: number; displayName: string; checkIns: number }[] };
  type CheckIn = { checkInId: number; studentId: number; studentName: string; locationName: string; checkInDate: string; checkedInAtUtc: string };
  let period = 'month'; let leaderboard: Leaderboard | null = null; let history: CheckIn[] = []; let from = new Date(Date.now() - 29 * 86400000).toISOString().slice(0, 10); let to = new Date().toISOString().slice(0, 10); let loading = true; let error = ''; let notice = '';
  async function load() { loading = true; error = ''; try { const end = new Date(`${to}T00:00:00`); end.setDate(end.getDate() + 1); const endDate = end.toISOString().slice(0, 10); [leaderboard, history] = await Promise.all([api<Leaderboard>(`/api/portal-admin/check-ins/leaderboard?period=${period}`), api<CheckIn[]>(`/api/portal-admin/check-ins/history?from=${from}&to=${endDate}`)]); } catch (e) { error = e instanceof Error ? e.message : 'Could not load check-in operations.'; } finally { loading = false; } }
  onMount(load);
</script>
<svelte:head><title>Staff · Check-ins | Task Karate</title></svelte:head>
<div class="toolbar"><div><span class="eyebrow">DOJO PRESENCE</span><h2>Check-ins & rankings</h2><p class="muted">Review HIYAH! activity, confirm competition standings, and keep the once-per-calendar-day rule visible to staff.</p></div><div class="toolbar-actions"><a class="button" href="/staff/students">Find a student</a></div></div>
{#if error}<div class="error" role="alert">{error}</div>{/if}{#if notice}<div class="status" role="status">{notice}</div>{/if}
<section class="card check-in-rule-banner"><div><span class="eyebrow">ANTI-SPAM RULE</span><h3>One studio check-in per student per calendar day</h3><p class="muted">The database uniqueness rule and API validation enforce this. Refreshing the page or returning to the student hub cannot create another check-in.</p></div><span class="pill">Server enforced</span></section>
<div class="admin-detail-grid"><section class="card"><div class="section-heading"><div><span class="eyebrow">COMPETITION</span><h3>Leaderboard</h3></div><div class="segmented-control"><button class:active={period === 'month'} type="button" on:click={() => { period = 'month'; load(); }}>This month</button><button class:active={period === 'year'} type="button" on:click={() => { period = 'year'; load(); }}>This year</button></div></div>{#if loading}<p class="muted">Loading rankings…</p>{:else if leaderboard?.entries.length}<div class="admin-leaderboard">{#each leaderboard.entries as entry}<a href={`/staff/students/${entry.studentId}`}><span class="leaderboard-rank">{entry.rank}</span><span><strong>{entry.displayName}</strong><small>{entry.checkIns} check-in{entry.checkIns === 1 ? '' : 's'} · {leaderboard?.periodLabel}</small></span><span class="pill">HIYAH!</span></a>{/each}</div>{:else}<div class="empty-state"><strong>No check-ins in this period.</strong><p class="muted">The race starts with the next student visit.</p></div>{/if}</section><section class="card"><div class="section-heading"><div><span class="eyebrow">HISTORY</span><h3>Recent check-ins</h3></div><span class="pill">{history.length}</span></div><div class="form-grid check-in-date-controls"><label>From<input type="date" bind:value={from} on:change={load} /></label><label>Through<input type="date" bind:value={to} on:change={load} /></label></div>{#if loading}<p class="muted">Loading history…</p>{:else if history.length}<div class="admin-check-in-history">{#each history.slice(0, 12) as item}<a href={`/staff/students/${item.studentId}`}><span class="admin-avatar">{item.studentName.slice(0, 1)}</span><span><strong>{item.studentName}</strong><small>{item.checkInDate} · {item.locationName}</small></span><span class="muted">{new Date(item.checkedInAtUtc).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</span></a>{/each}</div>{:else}<p class="muted">No check-ins in this date range.</p>{/if}</section></div>
