<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import StudentShell from '$lib/components/StudentShell.svelte';
  import { apiError, requireStudent, type StudentSession } from '$lib/student-session';
  let session: StudentSession | null = null; let profile: any = null; let nextClass: any = null; let timeline: any[] = []; let events: any[] = []; let goals: any[] = []; let error = ''; let loading = true;
  onMount(async () => { session = await requireStudent(); if (!session) return; try { [profile, nextClass, timeline, events, goals] = await Promise.all([api('/api/student/profile'), api<any[]>('/api/student/public/schedule').then((items) => items.find((item) => !item.cancelled) ?? null), api<any[]>('/api/student/timeline'), api<any[]>('/api/student/gold-stars'), api<any[]>('/api/student/goals')]); } catch (e) { error = apiError(e); } finally { loading = false; } });
  $: month = new Date().toLocaleString(undefined, { month: 'long' });
  $: stripePercent = profile?.classesPerStripe ? Math.min(100, (profile.classesIntoStripe / profile.classesPerStripe) * 100) : 0;
  function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
  $: attendanceSet = new Set(profile?.attendanceDates ?? []);
  $: attendanceDays = Array.from({ length: 30 }, (_, index) => { const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() - (29 - index)); const key = dateKey(date); return { key, day: date.getDate(), label: date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }), attended: attendanceSet.has(key), noClass: date.getDay() === 0 }; });
  function mondayStart() { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; }
  $: weekStart = mondayStart();
  $: weeklyClasses = (profile?.attendanceDates ?? []).filter((value: string) => new Date(`${value}T12:00:00`).getTime() >= weekStart.getTime()).length;
  $: streak = (() => { let count = 0; const cursor = new Date(); cursor.setHours(12, 0, 0, 0); for (let i = 0; i < 30; i += 1) { if (attendanceSet.has(dateKey(cursor))) count += 1; else if (cursor.getDay() !== 0) break; cursor.setDate(cursor.getDate() - 1); } return count; })();
  $: profileFields = [profile?.email, profile?.phone, profile?.uniformSize, profile?.beltSize, profile?.guardians?.length, profile?.programs?.length];
  $: profileCompletion = profile ? Math.round((profileFields.filter(Boolean).length / profileFields.length) * 100) : 0;
  $: featuredEvent = events.find((event) => !event.awarded && event.eventDate && new Date(event.eventDate).getTime() >= new Date().setHours(0, 0, 0, 0));
  $: daysUntilClass = nextClass ? Math.max(0, Math.ceil((new Date(nextClass.sessionDate).setHours(12, 0, 0, 0) - new Date().setHours(12, 0, 0, 0)) / 86400000)) : null;
  function calendarStamp(dateText: string, timeText: string | null) { const date = new Date(`${dateText}T12:00:00`); const [hours, minutes] = (timeText ?? '09:00').split(':').map(Number); date.setHours(hours, minutes, 0, 0); return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z'); }
  function addNextClassToCalendar() { if (!nextClass) return; const start = calendarStamp(nextClass.sessionDate, nextClass.startTime); const end = calendarStamp(nextClass.sessionDate, nextClass.endTime ?? nextClass.startTime); const ics = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Task Karate//Student Hub//EN', 'BEGIN:VEVENT', `UID:task-karate-${nextClass.sessionId}@local`, `DTSTART:${start}`, `DTEND:${end}`, `SUMMARY:${nextClass.className}`, `LOCATION:${nextClass.location ?? 'Main dojo'}`, 'END:VEVENT', 'END:VCALENDAR'].join('\r\n'); const url = URL.createObjectURL(new Blob([ics], { type: 'text/calendar' })); const link = document.createElement('a'); link.href = url; link.download = 'task-karate-next-class.ics'; link.click(); URL.revokeObjectURL(url); }
</script>

<svelte:head><title>Task Karate | Status dashboard</title></svelte:head>

{#if session}
  <StudentShell {session} active="status">
    <section class="student-heading"><span class="student-eyebrow">STUDENT HUB / TODAY</span><h1>STATUS DASHBOARD</h1><p>{session.displayName} · {profile?.rankName ?? 'Rank in progress'}. A clear view of your training day.</p></section>
    {#if loading}<div class="student-panel">Loading your training record…</div>{:else if error}<div class="student-panel error">{error}</div>{:else}
      <div class="metric-grid dark-metrics"><article><span>CLASSES THIS MONTH</span><strong>{profile?.classesThisMonth ?? 0}</strong><small>{month}</small></article><article><span>TOTAL CLASSES</span><strong>{profile?.totalClasses ?? 0}</strong><small>attendance records</small></article><a class="metric-link" href="/student/social?focus=messages" title="Open your messages"><span>UNREAD MESSAGES</span><strong>{profile?.unreadMessages ?? 0}</strong><small>Open messages →</small></a><a class="metric-link" href="/student/achievements" title="Open your achievements"><span>ACHIEVEMENTS</span><strong>{profile?.achievementCount ?? 0}</strong><small>Open achievements →</small></a></div>
      <div class="briefing-grid"><section class="student-panel briefing-card"><div class="panel-title"><span>WEEKLY MOMENTUM</span><span class="muted">Goal: 2 classes</span></div><div class="briefing-number">{weeklyClasses}<small>/ 2</small></div><div class="mini-progress"><span style={`width:${Math.min(100, weeklyClasses * 50)}%`}></span></div><p>{streak ? `${streak}-day attendance streak. Keep the rhythm going.` : 'Your next class can start this week’s streak.'}</p></section><section class="student-panel briefing-card"><div class="panel-title"><span>PROFILE READINESS</span><a href="/student/profile">Complete profile →</a></div><div class="briefing-number">{profileCompletion}<small>%</small></div><div class="mini-progress"><span style={`width:${profileCompletion}%`}></span></div><p>Uniform, belt, contact, guardian, and program details help staff support you.</p></section>{#if featuredEvent}<section class="student-panel briefing-card event-spotlight"><div class="panel-title"><span>UP NEXT AT THE DOJO</span><span class="gold-text">★ Gold Star</span></div><h2>{featuredEvent.name}</h2><p>{featuredEvent.description}</p><a class="text-link" href={`/student/achievements/${featuredEvent.eventId}`}>View event details →</a></section>{/if}</div>
      <div class="student-grid two-column"><section class="student-panel stripe-panel"><div class="panel-title"><span>STRIPE PROGRESS</span><a href="/student/profile">View profile →</a></div><div class="rank-display"><span class="rank-orb">{profile?.rankName?.slice(0, 1) ?? 'TK'}</span><div><h2>{profile?.rankName ?? 'White Belt'}</h2><p>{profile?.nextMilestone ?? 'Keep showing up and sharpen the fundamentals.'}</p></div></div>{#if profile?.classesPerStripe}<div class="stripe-track" aria-label={`${profile.classesIntoStripe} of ${profile.classesPerStripe} classes toward next stripe`}><span style={`width:${stripePercent}%`}></span></div><div class="stripe-summary"><strong>{profile.classesToNextStripe} {profile.classesToNextStripe === 1 ? 'class' : 'classes'} until next stripe</strong><span>{profile.classesIntoStripe} of {profile.classesPerStripe} completed</span></div>{:else}<div class="degree-note"><strong>Black belt degrees are instructor tracked.</strong><span>Degree timing begins at 2 years for second degree, then adds a year for each successive degree.</span></div>{/if}</section><section class="student-panel"><div class="panel-title"><span>PERSONAL RECORDS</span><a href="/student/check-in">Check in →</a></div><div class="record-list"><div><span>Member since</span><strong>{profile?.joinDate ?? 'On file'}</strong></div><div><span>Attendance streak</span><strong>{profile?.attendanceDates?.length ?? 0} recent</strong></div><div><span>Next action</span><strong>Choose today’s class</strong></div></div></section></div>
      <section class="student-panel next-class-panel"><div class="panel-title"><span>NEXT CLASS</span><a href="/student/check-in">Open check-in →</a></div>{#if nextClass}<div class="next-class-content"><div><span class="student-eyebrow">{new Date(nextClass.sessionDate).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</span><h2>{nextClass.className}</h2><p>{nextClass.startTime} – {nextClass.endTime} · {nextClass.location ?? 'Main dojo'} · {daysUntilClass === 0 ? 'Today' : `in ${daysUntilClass} days`}</p></div><div class="next-class-actions"><a class="primary-button" href="/student/check-in">Open check-in</a><button class="outline-button" type="button" on:click={addNextClassToCalendar}>Add to calendar</button></div></div>{:else}<p class="muted">No upcoming class is published yet.</p>{/if}</section><section class="student-panel goal-summary-panel"><div class="panel-title"><span>ACTIVE GOALS</span><a href="/student/training">Open training →</a></div>{#if goals.filter((goal) => !goal.completed).length}<div class="goal-summary-list">{#each goals.filter((goal) => !goal.completed).slice(0, 3) as goal}<div><span class="journey-dot"></span><strong>{goal.title}</strong>{#if goal.targetDate}<small>Target {new Date(goal.targetDate).toLocaleDateString()}</small>{/if}</div>{/each}</div>{:else}<p class="muted">Set your next training goal in the Training tab.</p>{/if}</section><section class="student-panel attendance-calendar-panel"><div class="panel-title"><span>ATTENDANCE · LAST 30 DAYS</span><a href="/student/check-in">Check in →</a></div><p class="muted">A green day means you attended. Sundays are shown as no-class days.</p><div class="attendance-calendar" aria-label="Attendance for the last 30 days">{#each attendanceDays as item}<span class:present={item.attended} class:no-class={item.noClass} title={`${item.label}: ${item.noClass ? 'No class' : item.attended ? 'Attended' : 'No attendance recorded'}`}>{item.day}</span>{/each}</div><div class="attendance-legend"><span><i class="legend-present"></i> Attended</span><span><i class="legend-empty"></i> No attendance</span><span><i class="legend-no-class"></i> Sunday · no class</span></div></section><section class="student-panel journey-panel"><div class="panel-title"><span>YOUR JOURNEY</span><span class="muted">Recent progress</span></div>{#if timeline.length}<div class="journey-list">{#each timeline.slice(0, 6) as item}<a class="journey-item" href={item.link ?? '/student'}><span class={`journey-dot ${item.type}`}></span><span><strong>{item.title}</strong><small>{item.description}</small><em>{new Date(item.occurredAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</em></span><b>→</b></a>{/each}</div>{:else}<p class="muted">Your training milestones will appear here as you attend, practice, and participate.</p>{/if}</section>
    {/if}
  </StudentShell>
{/if}
