<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import StudentShell from '$lib/components/StudentShell.svelte';
  import { apiError, requireStudent, type StudentSession } from '$lib/student-session';
  import { triggerEasterEgg } from '$lib/easter-eggs';
  let session: StudentSession | null = null; let profile: any = null; let nextClass: any = null; let timeline: any[] = []; let events: any[] = []; let goals: any[] = []; let error = ''; let loading = true;
  let activityQuery = ''; let activityFilter = 'all'; let journalText = ''; let savedJournal = ''; let monthlyTarget = 8; let targetDraft = '8'; let journalNotice = ''; let reminderNotice = '';
  let rankOrbClicks = 0; let rankOrbLastClick = 0; let beltOrbit = false;
  onMount(async () => { session = await requireStudent(); if (!session) return; savedJournal = localStorage.getItem(`task-karate-journal-${session.studentId}`) ?? ''; journalText = savedJournal; targetDraft = localStorage.getItem(`task-karate-monthly-target-${session.studentId}`) ?? '8'; monthlyTarget = Number(targetDraft) || 8; try { [profile, nextClass, timeline, events, goals] = await Promise.all([api('/api/student/profile'), api<any[]>('/api/student/public/schedule').then((items) => items.find((item) => !item.cancelled) ?? null), api<any[]>('/api/student/timeline'), api<any[]>('/api/student/gold-stars'), api<any[]>('/api/student/goals')]); } catch (e) { error = apiError(e); } finally { loading = false; } });
  $: month = new Date().toLocaleString(undefined, { month: 'long' });
  $: stripePercent = profile?.classesPerStripe ? Math.min(100, (profile.classesIntoStripe / profile.classesPerStripe) * 100) : 0;
  function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
  $: attendanceSet = new Set(profile?.attendanceDates ?? []);
  $: attendanceDays = Array.from({ length: 30 }, (_, index) => { const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() - (29 - index)); const key = dateKey(date); return { key, day: date.getDate(), label: date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }), attended: attendanceSet.has(key), noClass: date.getDay() === 0 }; });
  function mondayStart() { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; }
  $: weekStart = mondayStart();
  $: weeklyClasses = (profile?.attendanceDates ?? []).filter((value: string) => new Date(`${value}T12:00:00`).getTime() >= weekStart.getTime()).length;
  $: streak = (() => { let count = 0; const cursor = new Date(); cursor.setHours(12, 0, 0, 0); for (let i = 0; i < 30; i += 1) { if (attendanceSet.has(dateKey(cursor))) count += 1; else if (cursor.getDay() !== 0) break; cursor.setDate(cursor.getDate() - 1); } return count; })();
  $: isAdultStudent = profile ? (profile.birthDate ? new Date(profile.birthDate).getTime() <= new Date(new Date().setFullYear(new Date().getFullYear() - 18)).getTime() : profile.ageGroup?.trim().toLowerCase() === 'adult') : false;
  $: profileFields = [profile?.email, profile?.phone, profile?.uniformSize, profile?.beltSize, isAdultStudent || profile?.guardians?.length, profile?.programs?.length];
  $: profileCompletion = profile ? Math.round((profileFields.filter(Boolean).length / profileFields.length) * 100) : 0;
  $: featuredEvent = events.find((event) => !event.awarded && event.eventDate && new Date(event.eventDate).getTime() >= new Date().setHours(0, 0, 0, 0));
  $: filteredTimeline = timeline.filter((item) => { const matchesQuery = !activityQuery.trim() || `${item.title} ${item.description}`.toLowerCase().includes(activityQuery.trim().toLowerCase()); const matchesFilter = activityFilter === 'all' || item.type === activityFilter; return matchesQuery && matchesFilter; });
  $: attendanceRate = Math.round(Math.min(100, ((profile?.attendanceDates?.length ?? 0) / 30) * 100));
  $: bestTrainingDay = (() => { const counts: Record<string, number> = {}; (profile?.attendanceDates ?? []).forEach((value: string) => { const day = new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long' }); counts[day] = (counts[day] ?? 0) + 1; }); return Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'Not enough data'; })();
  $: nextAction = profile?.classesToNextStripe ? `${profile.classesToNextStripe} class${profile.classesToNextStripe === 1 ? '' : 'es'} until your next stripe.` : 'Your instructor tracks your next degree milestone.';
  $: daysUntilClass = nextClass ? Math.max(0, Math.ceil((new Date(nextClass.sessionDate).setHours(12, 0, 0, 0) - new Date().setHours(12, 0, 0, 0)) / 86400000)) : null;
  function calendarStamp(dateText: string, timeText: string | null) { const date = new Date(`${dateText}T12:00:00`); const [hours, minutes] = (timeText ?? '09:00').split(':').map(Number); date.setHours(hours, minutes, 0, 0); return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z'); }
  function addNextClassToCalendar() { if (!nextClass) return; const start = calendarStamp(nextClass.sessionDate, nextClass.startTime); const end = calendarStamp(nextClass.sessionDate, nextClass.endTime ?? nextClass.startTime); const ics = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Task Karate//Student Hub//EN', 'BEGIN:VEVENT', `UID:task-karate-${nextClass.sessionId}@local`, `DTSTART:${start}`, `DTEND:${end}`, `SUMMARY:${nextClass.className}`, `LOCATION:${nextClass.location ?? 'Main dojo'}`, 'END:VEVENT', 'END:VCALENDAR'].join('\r\n'); const url = URL.createObjectURL(new Blob([ics], { type: 'text/calendar' })); const link = document.createElement('a'); link.href = url; link.download = 'task-karate-next-class.ics'; link.click(); URL.revokeObjectURL(url); }
  function saveJournal() { if (!session) return; savedJournal = journalText.trim(); localStorage.setItem(`task-karate-journal-${session.studentId}`, savedJournal); journalNotice = savedJournal ? 'Private note saved on this device.' : 'Private note cleared.'; window.setTimeout(() => journalNotice = '', 2500); }
  function saveTarget() { if (!session) return; monthlyTarget = Math.max(1, Math.min(31, Number(targetDraft) || 8)); targetDraft = String(monthlyTarget); localStorage.setItem(`task-karate-monthly-target-${session.studentId}`, targetDraft); }
  function clickRankOrb() { const now = Date.now(); if (now - rankOrbLastClick > 2200) rankOrbClicks = 0; rankOrbLastClick = now; rankOrbClicks += 1; if (rankOrbClicks >= 3) { rankOrbClicks = 0; beltOrbit = true; window.setTimeout(() => beltOrbit = false, 1800); triggerEasterEgg('egg-belt-whisperer'); } }
  function enableClassReminder() { if (!nextClass) { reminderNotice = 'There is no upcoming class to remind you about yet.'; return; } if (!('Notification' in window)) { reminderNotice = 'Notifications are not available in this browser. Use Add to calendar instead.'; return; } Notification.requestPermission().then((permission) => { if (permission !== 'granted') { reminderNotice = 'Notifications stayed off. Your calendar export is still available.'; return; } const ms = new Date(`${nextClass.sessionDate}T${nextClass.startTime ?? '09:00'}`).getTime() - Date.now() - 30 * 60 * 1000; reminderNotice = ms > 0 ? 'Reminder armed for 30 minutes before your next class while this page stays open.' : 'Your next class is soon — reminder is ready for this session.'; if (ms > 0) window.setTimeout(() => new Notification(`Task Karate: ${nextClass.className}`, { body: 'Your class starts in 30 minutes.' }), ms); }); }
</script>

<svelte:head><title>Task Karate | Status dashboard</title></svelte:head>

{#if session}
  <StudentShell {session} active="status">
    <section class="student-heading"><span class="student-eyebrow">STUDENT HUB / TODAY</span><h1>STATUS DASHBOARD</h1><p>{session.displayName} · {profile?.rankName ?? 'Rank in progress'}. A clear view of your training day.</p></section>
    {#if loading}<div class="student-panel">Loading your training record…</div>{:else if error}<div class="student-panel error">{error}</div>{:else}
      <div class="metric-grid dark-metrics"><article><span>CLASSES THIS MONTH</span><strong>{profile?.classesThisMonth ?? 0}</strong><small>{month}</small></article><article><span>TOTAL CLASSES</span><strong>{profile?.totalClasses ?? 0}</strong><small>attendance records</small></article><a class="metric-link" href="/student/social?focus=messages" title="Open your messages"><span>UNREAD MESSAGES</span><strong>{profile?.unreadMessages ?? 0}</strong><small>Open messages →</small></a><a class="metric-link" href="/student/achievements" title="Open your achievements"><span>ACHIEVEMENTS</span><strong>{profile?.achievementCount ?? 0}</strong><small>Open achievements →</small></a></div>
      <div class="briefing-grid"><section class="student-panel briefing-card"><div class="panel-title"><span>WEEKLY MOMENTUM</span><span class="muted">Goal: 2 classes</span></div><div class="briefing-number">{weeklyClasses}<small>/ 2</small></div><div class="mini-progress"><span style={`width:${Math.min(100, weeklyClasses * 50)}%`}></span></div><p>{streak ? `${streak}-day attendance streak. Keep the rhythm going.` : 'Your next class can start this week’s streak.'}</p></section><section class="student-panel briefing-card"><div class="panel-title"><span>PROFILE READINESS</span>{#if profileCompletion >= 100}<span class="readiness-complete">✓ READY FOR THE MAT</span>{:else}<a href="/student/profile">Complete profile →</a>{/if}</div>{#if profileCompletion >= 100}<div class="briefing-complete"><strong>READY</strong><span>Your profile is complete and ready to represent you.</span></div>{:else}<div class="briefing-number">{profileCompletion}<small>%</small></div>{/if}<div class="mini-progress"><span style={`width:${profileCompletion}%`}></span></div><p>{profileCompletion >= 100 ? 'Everything staff needs is on file. Keep your story fresh from your profile.' : `Uniform, belt, contact, ${isAdultStudent ? 'emergency contact, ' : 'guardian, '}and program details help staff support you.`}</p></section>{#if featuredEvent}<section class="student-panel briefing-card event-spotlight"><div class="panel-title"><span>UP NEXT AT THE DOJO</span><span class="gold-text">★ Gold Star</span></div><h2>{featuredEvent.name}</h2><p>{featuredEvent.description}</p><a class="text-link" href={`/student/achievements/${featuredEvent.eventId}`}>View event details →</a></section>{:else}<section class="student-panel briefing-card next-action-card"><div class="panel-title"><span>NEXT TRAINING ACTION</span><a href="/student/training">Open training →</a></div><div class="briefing-number">{profile?.classesToNextStripe ?? '—'}<small>{profile?.classesToNextStripe ? ' classes' : ''}</small></div><p>{nextAction}</p></section>{/if}</div>
      <div class="student-grid two-column"><section class="student-panel stripe-panel"><div class="panel-title"><span>STRIPE PROGRESS</span><a href="/student/profile">View profile →</a></div><div class="rank-display"><button class:belt-orbit={beltOrbit} class="rank-orb" type="button" on:click={clickRankOrb} aria-label="Current rank — hidden belt color easter egg">{profile?.rankName?.slice(0, 1) ?? 'TK'}</button><div><h2>{profile?.rankName ?? 'White Belt'}</h2><p>{profile?.nextMilestone ?? 'Keep showing up and sharpen the fundamentals.'}</p></div></div>{#if profile?.classesPerStripe}<div class="stripe-track" aria-label={`${profile.classesIntoStripe} of ${profile.classesPerStripe} classes toward next stripe`}><span style={`width:${stripePercent}%`}></span></div><div class="stripe-summary"><strong>{profile.classesToNextStripe} {profile.classesToNextStripe === 1 ? 'class' : 'classes'} until next stripe</strong><span>{profile.classesIntoStripe} of {profile.classesPerStripe} completed</span></div>{:else}<div class="degree-note"><strong>Black belt degrees are instructor tracked.</strong><span>Degree timing begins at 2 years for second degree, then adds a year for each successive degree.</span></div>{/if}</section><section class="student-panel"><div class="panel-title"><span>PERSONAL RECORDS</span><a href="/student/check-in">Check in →</a></div><div class="record-list"><div><span>Member since</span><strong>{profile?.joinDate ?? 'On file'}</strong></div><div><span>Attendance streak</span><strong>{profile?.attendanceDates?.length ?? 0} recent</strong></div><div><span>Next action</span><strong>Choose today’s class</strong></div></div></section></div>
      <div class="dashboard-tools-grid"><section class="student-panel insight-panel"><div class="panel-title"><span>ATTENDANCE INSIGHTS</span><span class="muted">Last 30 days</span></div><div class="insight-metrics"><div><strong>{attendanceRate}%</strong><small>attendance rate</small></div><div><strong>{bestTrainingDay}</strong><small>strongest training day</small></div><div><strong>{profile?.attendanceDates?.length ?? 0}</strong><small>recorded visits</small></div></div><div class="target-row"><span>Monthly target · {profile?.classesThisMonth ?? 0} / {monthlyTarget}</span><input aria-label="Monthly class target" type="number" min="1" max="31" bind:value={targetDraft} on:change={saveTarget} /></div><div class="mini-progress"><span style={`width:${Math.min(100, ((profile?.classesThisMonth ?? 0) / monthlyTarget) * 100)}%`}></span></div></section><section class="student-panel journal-panel"><div class="panel-title"><span>PRIVATE TRAINING NOTE</span><span class="muted">Only on this device</span></div><textarea bind:value={journalText} maxlength="1000" placeholder="Capture what clicked today, a question for your instructor, or a promise to yourself…" aria-label="Private training note"></textarea><div class="journal-footer"><span class="muted">{journalText.length}/1000</span><button class="outline-button" type="button" on:click={saveJournal}>Save note</button></div>{#if journalNotice}<p class="tools-notice" role="status">{journalNotice}</p>{/if}</section></div>
      <section class="student-panel next-class-panel"><div class="panel-title"><span>NEXT CLASS</span><a href="/student/check-in">Open check-in →</a></div>{#if nextClass}<div class="next-class-content"><div><span class="student-eyebrow">{new Date(nextClass.sessionDate).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</span><h2>{nextClass.className}</h2><p>{nextClass.startTime} – {nextClass.endTime} · {nextClass.location ?? 'Main dojo'} · {daysUntilClass === 0 ? 'Today' : `in ${daysUntilClass} days`}</p></div><div class="next-class-actions"><a class="primary-button" href="/student/check-in">Open check-in</a><button class="outline-button" type="button" on:click={addNextClassToCalendar}>Add to calendar</button></div></div>{:else}<p class="muted">No upcoming class is published yet.</p>{/if}</section><section class="student-panel goal-summary-panel"><div class="panel-title"><span>ACTIVE GOALS</span><a href="/student/training">Open training →</a></div>{#if goals.filter((goal) => !goal.completed).length}<div class="goal-summary-list">{#each goals.filter((goal) => !goal.completed).slice(0, 3) as goal}<div><span class="journey-dot"></span><strong>{goal.title}</strong>{#if goal.targetDate}<small>Target {new Date(goal.targetDate).toLocaleDateString()}</small>{/if}</div>{/each}</div>{:else}<p class="muted">Set your next training goal in the Training tab.</p>{/if}</section><section class="student-panel attendance-calendar-panel"><div class="panel-title"><span>ATTENDANCE · LAST 30 DAYS</span><a href="/student/check-in">Check in →</a></div><p class="muted">A green day means you attended. Sundays are shown as no-class days.</p><div class="attendance-calendar" aria-label="Attendance for the last 30 days">{#each attendanceDays as item}<span class:present={item.attended} class:no-class={item.noClass} title={`${item.label}: ${item.noClass ? 'No class' : item.attended ? 'Attended' : 'No attendance recorded'}`}>{item.day}</span>{/each}</div><div class="attendance-legend"><span><i class="legend-present"></i> Attended</span><span><i class="legend-empty"></i> No attendance</span><span><i class="legend-no-class"></i> Sunday · no class</span></div></section><section class="student-panel journey-panel"><div class="panel-title"><span>YOUR JOURNEY</span><span class="muted">Recent progress</span></div>{#if timeline.length}<div class="journey-list">{#each timeline.slice(0, 6) as item}<a class="journey-item" href={item.link ?? '/student'}><span class={`journey-dot ${item.type}`}></span><span><strong>{item.title}</strong><small>{item.description}</small><em>{new Date(item.occurredAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</em></span><b>→</b></a>{/each}</div>{:else}<p class="muted">Your training milestones will appear here as you attend, practice, and participate.</p>{/if}</section>
    {/if}
  </StudentShell>
{/if}
