<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import type { Content } from '$lib/types';
  let items: Content[] = []; let title = ''; let body = ''; let error = ''; let notice = ''; let loading = true; let saving = false; let publishingId = ''; let statusFilter = 'All';
  async function load() { loading = true; try { items = await api<Content[]>('/api/news'); } catch (e) { error = e instanceof Error ? e.message : 'Could not load news.'; } finally { loading = false; } }
  $: visibleItems = items.filter((item) => statusFilter === 'All' || item.status === statusFilter);
  async function create() { saving = true; error = ''; try { await api('/api/news', { method: 'POST', body: JSON.stringify({ title: title.trim(), body: body.trim() }) }); title = ''; body = ''; notice = 'News draft saved.'; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not save news.'; } finally { saving = false; } }
  async function publish(id: string) { publishingId = id; error = ''; try { await api(`/api/news/${id}/publish`, { method: 'POST' }); notice = 'News post published.'; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not publish news.'; } finally { publishingId = ''; } }
  onMount(load);
</script>
<svelte:head><title>Staff · News | Task Karate</title></svelte:head>
<div class="toolbar"><div><span class="eyebrow">PUBLIC CONTENT</span><h2>News</h2><p class="muted">Publish durable dojo stories separately from short-lived announcements.</p></div></div>
{#if error}<div class="error" role="alert">{error}</div>{/if}{#if notice}<div class="status" role="status">{notice}</div>{/if}
<section class="card"><div class="split"><div><h3>New news draft</h3><form class="form-grid" on:submit|preventDefault={create}><label class="full">Title<input bind:value={title} maxlength="160" required /><small class="muted">{title.length}/160</small></label><label class="full">Body<textarea bind:value={body} maxlength="5000" required></textarea><small class="muted">{body.length}/5000</small></label><div class="full"><button class="button" disabled={saving || !title.trim() || !body.trim()}>{saving ? 'Saving…' : 'Save draft'}</button></div></form></div><div class="content-preview"><span class="eyebrow">PREVIEW</span><h3>{title || 'News headline'}</h3><p>{body || 'Your news preview appears here before publication.'}</p></div></div></section>
<section class="card"><div class="section-heading"><div><h3>News queue</h3><span class="pill">{visibleItems.length}</span></div><label>Show<select bind:value={statusFilter}><option>All</option><option>Draft</option><option>Published</option></select></label></div>{#if loading}<p class="muted">Loading news queue…</p>{:else}{#each visibleItems as item}<article class="announcement"><div class="toolbar"><div><h3>{item.title}</h3><span class="pill">{item.status}</span></div>{#if item.status !== 'Published'}<button class="button small-button" disabled={publishingId === item.id} on:click={() => publish(item.id)}>{publishingId === item.id ? 'Publishing…' : 'Publish'}</button>{/if}</div><p>{item.body}</p>{#if item.publishedAtUtc}<small class="muted">Published {new Date(item.publishedAtUtc).toLocaleString()}</small>{/if}</article>{:else}<p class="muted">No news posts match this filter.</p>{/each}{/if}</section>
