<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import type { Content } from '$lib/types';
  let items: Content[] = []; let title = ''; let body = ''; let imageUrl = ''; let imageAlt = ''; let editorMode: 'write' | 'preview' = 'write'; let error = ''; let notice = ''; let loading = true; let saving = false; let publishingId = ''; let statusFilter = 'All';
  async function load() { loading = true; try { items = await api<Content[]>('/api/portal-admin/news'); } catch (e) { error = e instanceof Error ? e.message : 'Could not load news.'; } finally { loading = false; } }
  $: visibleItems = items.filter((item) => statusFilter === 'All' || item.status === statusFilter);
  function escapeHtml(value: string) { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function renderMarkdown(value: string) {
    let html = escapeHtml(value || 'Your news preview appears here before publication.');
    html = html.replace(/!\[([^\]]*)\]\((https?:\/\/[^\s)]+)\)/g, '<img src="$2" alt="$1" loading="lazy" />');
    html = html.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>');
    html = html.replace(/^### (.*)$/gm, '<h5>$1</h5>').replace(/^## (.*)$/gm, '<h4>$1</h4>').replace(/^# (.*)$/gm, '<h3>$1</h3>');
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*(.*?)\*/g, '<em>$1</em>');
    html = html.replace(/^(?:- )(.*)$/gm, '<li>$1</li>').replace(/(?:<li>.*<\/li>\n?)+/g, (list) => `<ul>${list}</ul>`);
    return html.replace(/\n/g, '<br />');
  }
  function insertMarkdown(token: string) { body = `${body}${body ? '\n\n' : ''}${token}`; }
  function insertImage() { if (!/^https?:\/\//i.test(imageUrl.trim())) { error = 'Image embeds must use an https:// or http:// URL.'; return; } insertMarkdown(`![${imageAlt.trim() || 'Task Karate image'}](${imageUrl.trim()})`); imageUrl = ''; imageAlt = ''; }
  async function create() { saving = true; error = ''; try { await api('/api/portal-admin/news', { method: 'POST', body: JSON.stringify({ title: title.trim(), body: body.trim() }) }); title = ''; body = ''; imageUrl = ''; imageAlt = ''; notice = 'News draft saved in the canonical portal database.'; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not save news.'; } finally { saving = false; } }
  async function publish(id: string) { publishingId = id; error = ''; try { await api(`/api/portal-admin/news/${id}/publish`, { method: 'POST' }); notice = 'News post published.'; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not publish news.'; } finally { publishingId = ''; } }
  onMount(load);
</script>
<svelte:head><title>Staff · News | Task Karate</title></svelte:head>
<div class="toolbar"><div><span class="eyebrow">PUBLIC CONTENT</span><h2>Public News</h2><p class="muted">Longer-lived dojo stories. The Noticeboard is for short operational notices; this queue is for publishable news and student-feed stories.</p></div></div>
{#if error}<div class="error" role="alert">{error}</div>{/if}{#if notice}<div class="status" role="status">{notice}</div>{/if}
<section class="card"><div class="split"><div><h3>New news draft</h3><form class="form-grid" on:submit|preventDefault={create}><label class="full">Title<input bind:value={title} maxlength="160" required /><small class="muted">{title.length}/160</small></label><div class="full editor-tabs"><button class:active={editorMode === 'write'} type="button" class="button secondary small-button" on:click={() => editorMode = 'write'}>Write markdown</button><button class:active={editorMode === 'preview'} type="button" class="button secondary small-button" on:click={() => editorMode = 'preview'}>Live preview</button></div>{#if editorMode === 'write'}<div class="full markdown-toolbar" aria-label="Markdown shortcuts"><button type="button" class="button secondary small-button" on:click={() => insertMarkdown('**Bold text**')}>Bold</button><button type="button" class="button secondary small-button" on:click={() => insertMarkdown('## Section heading')}>Heading</button><button type="button" class="button secondary small-button" on:click={() => insertMarkdown('- List item')}>List</button></div><label class="full">Body<textarea bind:value={body} maxlength="5000" rows="12" required placeholder="Write the story in markdown. Links, headings, emphasis, lists, and image embeds are supported."></textarea><small class="muted">{body.length}/5000 · Markdown is sanitized before preview.</small></label><div class="full image-embed-fields"><label>Image URL<input type="url" bind:value={imageUrl} placeholder="https://…" /></label><label>Alt text<input bind:value={imageAlt} placeholder="Describe the image" /></label><button type="button" class="button secondary small-button" on:click={insertImage} disabled={!imageUrl.trim()}>Insert image</button></div>{/if}<div class="full"><button class="button" disabled={saving || !title.trim() || !body.trim()}>{saving ? 'Saving…' : 'Save draft'}</button></div></form></div><div class="content-preview markdown-preview"><span class="eyebrow">LIVE PREVIEW</span><h3>{title || 'News headline'}</h3><div>{@html renderMarkdown(body)}</div></div></div></section>
<section class="card"><div class="section-heading"><div><h3>News queue</h3><span class="pill">{visibleItems.length}</span></div><label>Show<select bind:value={statusFilter}><option>All</option><option>Draft</option><option>Published</option></select></label></div>{#if loading}<p class="muted">Loading news queue…</p>{:else}{#each visibleItems as item}<article class="announcement"><div class="toolbar"><div><h3>{item.title}</h3><span class="pill">{item.status}</span></div>{#if item.status !== 'Published'}<button class="button small-button" disabled={publishingId === item.id} on:click={() => publish(item.id)}>{publishingId === item.id ? 'Publishing…' : 'Publish'}</button>{/if}</div><div class="queue-preview markdown-preview">{@html renderMarkdown(item.body)}</div>{#if item.publishedAtUtc}<small class="muted">Published {new Date(item.publishedAtUtc).toLocaleString()}</small>{/if}</article>{:else}<p class="muted">No news posts match this filter.</p>{/each}{/if}</section>
