<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import StudentShell from '$lib/components/StudentShell.svelte';
  import { apiError, requireStudent, type StudentSession } from '$lib/student-session';
  import { kidsTrainingPlans, nextRank, trainingPlans } from '$lib/training-requirements';
  import { is3LevelGuides } from '$lib/is3-levels';
  let session: StudentSession | null = null; let profile: any = null; let missions: any[] = []; let practiceLogs: any[] = []; let goals: any[] = []; let error = ''; let practiceSkill = ''; let practiceMinutes = 10; let practiceReflection = ''; let goalTitle = ''; let goalDate = '';
  onMount(async () => { session = await requireStudent(); if (!session) return; try { [profile, missions, practiceLogs, goals] = await Promise.all([api('/api/student/profile'), api<any[]>('/api/student/missions'), api<any[]>('/api/student/practice'), api<any[]>('/api/student/goals')]); } catch (e) { error = apiError(e); } });
  $: nextRankName = nextRank(profile?.rankName);
  $: karateTrack = profile?.ageGroup === 'kids' ? 'Kids Karate' : 'Teens & Adults Karate';
  $: plan = (profile?.ageGroup === 'kids' ? kidsTrainingPlans[nextRankName] : undefined) ?? trainingPlans[nextRankName] ?? trainingPlans['White Belt'];
  $: stripePercent = profile?.classesPerStripe ? Math.min(100, (profile.classesIntoStripe / profile.classesPerStripe) * 100) : 0;
  $: is3Program = profile?.programs?.find((program: any) => program.programCode === 'is3');
  $: is3Guide = is3LevelGuides[is3Program?.levelName ?? 'IS3 Student Level 0'] ?? is3LevelGuides['IS3 Student Level 0'];
  async function toggleMission(missionId: number) { try { await api(`/api/student/missions/${missionId}/toggle`, { method: 'POST' }); missions = await api<any[]>('/api/student/missions'); } catch (e) { error = apiError(e); } }
  async function logPractice() { if (!practiceSkill.trim()) return; try { await api('/api/student/practice', { method: 'POST', body: JSON.stringify({ skill: practiceSkill, minutes: Number(practiceMinutes), reflection: practiceReflection || null }) }); practiceSkill = ''; practiceMinutes = 10; practiceReflection = ''; practiceLogs = await api<any[]>('/api/student/practice'); } catch (e) { error = apiError(e); } }
  async function addGoal() { if (!goalTitle.trim()) return; try { await api('/api/student/goals', { method: 'POST', body: JSON.stringify({ title: goalTitle, targetDate: goalDate || null }) }); goalTitle = ''; goalDate = ''; goals = await api<any[]>('/api/student/goals'); } catch (e) { error = apiError(e); } }
  async function toggleGoal(goalId: number) { try { await api(`/api/student/goals/${goalId}/toggle`, { method: 'POST' }); goals = await api<any[]>('/api/student/goals'); } catch (e) { error = apiError(e); } }
</script>

<svelte:head><title>Task Karate | Training</title></svelte:head>

{#if session}
  <StudentShell {session} active="training">
    <section class="student-heading"><span class="student-eyebrow">YOUR PRACTICE RECORD · {karateTrack}</span><h1>TRAINING</h1><p>Know what you are working toward before your next rank check. Your requirements adapt to the programs and age track on your profile.</p></section>
    {#if error}<div class="error">{error}</div>{:else if !profile}<div class="student-panel loading-panel">Loading your training plan…</div>{:else}
      <div class="student-grid two-column training-top-grid">
        <section class="student-panel training-hero"><span class="belt-graphic" style={`--belt-color:${plan.color}`}><span class="belt-knot"></span><span class="belt-strip"></span></span><span class="student-eyebrow">NEXT RANK</span><h2>{nextRankName}</h2><p>{plan.promotionGuide}</p></section>
        <section class="student-panel stripe-panel"><div class="panel-title"><span>STRIPE PROGRESS</span><a href="/student/profile">View profile →</a></div><div class="stripe-track" aria-label={`${profile.classesIntoStripe} of ${profile.classesPerStripe || 0} classes toward next stripe`}><span style={`width:${stripePercent}%`}></span></div><div class="stripe-summary"><strong>{profile.classesToNextStripe || 'Instructor tracked'} {profile.classesToNextStripe ? (profile.classesToNextStripe === 1 ? 'class' : 'classes') : ''} until next stripe</strong><span>{profile.classesPerStripe ? `${profile.classesIntoStripe} of ${profile.classesPerStripe} completed` : 'Black belt degrees are tracked by your instructor.'}</span></div></section>
      </div>
      {#if is3Program}<section class="student-panel is3-panel"><div class="panel-title"><span>IS3 LEVEL TRACK</span><a href="/student/profile">View programs →</a></div><div class="is3-track-heading"><div class="program-code large">IS3</div><div><span class="student-eyebrow">CURRENT LEVEL</span><h2>{is3Guide.current}</h2><p>Next: {is3Guide.next}</p></div></div><div class="is3-focus-grid">{#each is3Guide.focus as focus}<div><span>FOCUS</span><strong>{focus}</strong></div>{/each}</div><p class="muted">{is3Guide.note}</p></section>{/if}
      <nav class="training-track-nav" aria-label="Training tracks"><a class="active" href="/student/training">Training overview</a><a href="/student/training/karate">Karate requirements</a>{#if is3Program}<a href="/student/training/is3">IS3 level track</a>{/if}</nav>
      <section class="student-panel training-note-panel"><div class="panel-title"><span>BELT TEST REQUIREMENTS</span><a href="/student/training/karate">Open Karate track →</a></div><p>{profile.favoriteTechnique ? `Current focus: ${profile.favoriteTechnique}. Open the Karate track for the full checklist and practice it with your instructor.` : 'Open the Karate track for the full belt-test checklist, organized for your age group and next rank.'}</p></section>
      <section class="student-panel mission-panel"><div class="panel-title"><span>PRACTICE MISSIONS</span><span class="muted">Small reps build big progress</span></div><div class="mission-grid">{#each missions as mission}<button class:completed={mission.completed} class="mission-card" type="button" on:click={() => toggleMission(mission.missionId)}><span class="mission-check">{mission.completed ? '✓' : '○'}</span><span><small>{mission.category}</small><strong>{mission.title}</strong><em>{mission.completed ? 'Completed · tap to reopen' : mission.description}</em></span></button>{/each}</div></section>
      <div class="training-tools-grid">
        <section class="student-panel practice-panel"><div class="panel-title"><span>PRACTICE LOG</span><span class="muted">Make the reps visible</span></div><form class="practice-form" on:submit|preventDefault={logPractice}><label>Skill or focus<input bind:value={practiceSkill} maxlength="100" placeholder="e.g. Roundhouse kick" /></label><label>Minutes<input type="number" min="1" max="240" bind:value={practiceMinutes} /></label><label class="full">Reflection<textarea bind:value={practiceReflection} maxlength="1000" rows="2" placeholder="What felt better today?"></textarea></label><button class="primary-button" type="submit" disabled={!practiceSkill.trim()}>Log practice</button></form>{#if practiceLogs.length}<div class="practice-log-list">{#each practiceLogs.slice(0, 3) as log}<div class="practice-log"><span class="practice-minutes">{log.minutes}<small>min</small></span><div><strong>{log.skill}</strong><p>{log.reflection ?? 'Practice recorded.'}</p><small>{new Date(log.loggedAt).toLocaleDateString()}</small></div></div>{/each}</div>{/if}</section>
        <section class="student-panel goals-panel"><div class="panel-title"><span>MY GOALS</span><span class="muted">Small targets, big momentum</span></div><form class="goal-form" on:submit|preventDefault={addGoal}><input bind:value={goalTitle} maxlength="160" placeholder="Add a training goal…" aria-label="New training goal" /><input type="date" bind:value={goalDate} aria-label="Goal target date" /><button class="outline-button" type="submit" disabled={!goalTitle.trim()}>Add goal</button></form><div class="goal-list">{#each goals as goal}<button type="button" class:completed={goal.completed} class="goal-row" on:click={() => toggleGoal(goal.goalId)}><span>{goal.completed ? '✓' : '○'}</span><span><strong>{goal.title}</strong><small>{goal.completed ? 'Completed · tap to reopen' : goal.targetDate ? `Target ${new Date(goal.targetDate).toLocaleDateString()}` : 'No target date'}</small></span></button>{:else}<p class="muted">Set a goal for your next class.</p>{/each}</div></section>
      </div>
    {/if}
  </StudentShell>
{/if}
