<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';

  type PortalStudent = { studentId: number; displayName: string; rankName?: string; ageGroup?: string; isActive: boolean; joinDate?: string; uniformSize?: string; beltSize?: string; bio?: string; favoriteTechnique?: string; totalClasses: number; attendanceStreak: number; achievementCount: number; goldStarCount: number; programs: string[] };
  type StudentForm = { firstName: string; lastName: string; preferredName: string; ageGroup: string; joinDate: string; uniformSize: string; beltSize: string; bio: string; favoriteTechnique: string };
  const blankForm = (): StudentForm => ({ firstName: '', lastName: '', preferredName: '', ageGroup: 'Kids', joinDate: new Date().toISOString().slice(0, 10), uniformSize: '', beltSize: '', bio: '', favoriteTechnique: '' });
  let students: PortalStudent[] = [];
  let form = blankForm();
  let editingId = '';
  let includeInactive = false;
  let query = '';
  let error = '';
  let notice = '';
  let loading = true;
  let saving = false;

  async function load() { loading = true; error = ''; try { students = await api<PortalStudent[]>('/api/portal-admin/students'); } catch (e) { error = e instanceof Error ? e.message : 'Could not load portal students.'; } finally { loading = false; } }
  $: visibleStudents = students.filter((student) => (includeInactive || student.isActive) && `${student.displayName} ${student.rankName ?? ''} ${student.programs.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
  function resetForm() { form = blankForm(); editingId = ''; }
  function edit(student: PortalStudent) { editingId = String(student.studentId); const parts = student.displayName.split(' '); form = { ...blankForm(), firstName: parts.shift() ?? '', lastName: parts.join(' '), preferredName: student.displayName, ageGroup: student.ageGroup === 'TeensAdults' ? 'TeensAdults' : 'Kids', joinDate: student.joinDate?.slice(0, 10) ?? blankForm().joinDate, uniformSize: student.uniformSize ?? '', beltSize: student.beltSize ?? '', bio: student.bio ?? '', favoriteTechnique: student.favoriteTechnique ?? '' }; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function save() { error = ''; notice = ''; saving = true; try { const payload = { ...form, joinDate: form.joinDate || null }; if (editingId) { await api(`/api/portal-admin/students/${editingId}`, { method: 'PUT', body: JSON.stringify(payload) }); notice = 'Student profile updated in the portal database.'; } else { await api('/api/portal-admin/students', { method: 'POST', body: JSON.stringify(payload) }); notice = 'Portal student created.'; } resetForm(); await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not save student.'; } finally { saving = false; } }
  async function setActive(student: PortalStudent, active: boolean) { error = ''; try { await api(`/api/portal-admin/students/${student.studentId}/active`, { method: 'POST', body: JSON.stringify({ active }) }); notice = active ? 'Student reactivated.' : 'Student deactivated.'; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not update student status.'; } }
  onMount(load);
</script>

<svelte:head><title>Staff · Students | Task Karate</title></svelte:head>
<div class="toolbar"><div><span class="eyebrow">PORTAL PEOPLE</span><h2>Student profiles</h2><p class="muted">This roster reads and writes the same database used by the student hub. Changes are audited.</p></div></div>
{#if error}<div class="error" role="alert">{error}</div>{/if}{#if notice}<div class="status" role="status">{notice}</div>{/if}
<section class="card"><div class="section-heading"><div><h3>{editingId ? 'Edit portal profile' : 'Create portal student'}</h3><p class="muted">Keep private notes appropriate for staff use. Passwords are managed separately through the secure account workflow.</p></div>{#if editingId}<button class="button secondary small-button" type="button" on:click={resetForm}>Cancel edit</button>{/if}</div><form class="form-grid" on:submit|preventDefault={save}><label>First name<input bind:value={form.firstName} required /></label><label>Last name<input bind:value={form.lastName} required /></label><label>Display name<input bind:value={form.preferredName} placeholder="Shown to students" /></label><label>Age group<select bind:value={form.ageGroup}><option value="Kids">Kids</option><option value="TeensAdults">Teens & Adults</option></select></label><label>Join date<input type="date" bind:value={form.joinDate} required /></label><label>Uniform size<input bind:value={form.uniformSize} /></label><label>Belt size<input bind:value={form.beltSize} /></label><label>Favorite technique<input bind:value={form.favoriteTechnique} /></label><label class="full">Profile note<textarea bind:value={form.bio} maxlength="1000"></textarea></label><div class="full"><button class="button" disabled={saving}>{saving ? 'Saving…' : editingId ? 'Save profile changes' : 'Create portal student'}</button></div></form></section>
<section class="card"><div class="section-heading"><div><h3>{includeInactive ? 'All portal records' : 'Active portal roster'}</h3><span class="pill">{visibleStudents.length}</span></div><div class="staff-list-controls"><input bind:value={query} type="search" placeholder="Search portal students…" aria-label="Search portal students" /><label class="check-row"><input type="checkbox" bind:checked={includeInactive} /> Include inactive</label></div></div>{#if loading}<p class="muted">Loading portal database…</p>{:else}<div class="table-wrap"><table><thead><tr><th>Student</th><th>Programs</th><th>Classes</th><th>Recognition</th><th>Status</th><th>Actions</th></tr></thead><tbody>{#each visibleStudents as student}<tr><td><strong>{student.displayName}</strong><small class="table-subtext">{student.rankName ?? 'Rank not assigned'} · {student.ageGroup ?? 'Age group not set'}</small></td><td>{student.programs.join(', ') || 'No program'}</td><td>{student.totalClasses} · {student.attendanceStreak} day streak</td><td>{student.achievementCount} achievements · {student.goldStarCount} Gold Stars</td><td><span class:inactive={!student.isActive} class="pill">{student.isActive ? 'Active' : 'Inactive'}</span></td><td><div class="table-actions"><button class="button secondary small-button" type="button" on:click={() => edit(student)}>Edit profile</button>{#if student.isActive}<button class="button danger small-button" type="button" on:click={() => setActive(student, false)}>Deactivate</button>{:else}<button class="button secondary small-button" type="button" on:click={() => setActive(student, true)}>Reactivate</button>{/if}</div></td></tr>{:else}<tr><td colspan="6" class="muted">No portal students match this view.</td></tr>{/each}</tbody></table></div>{/if}</section>
