(async () => {
  const mount = document.querySelector("[data-portal-view]");
  if (!mount) return;
  if (sessionStorage.getItem("task-karate-demo-session") !== "active") {
    mount.innerHTML = '<div class="portal-card"><h2>Student login required</h2><p>Sign in to open the demo portal experience.</p><a class="button" href="login.html">Go to student login</a></div>';
    return;
  }
  const view = document.body.dataset.view || "dashboard";
  try {
    const student = await fetch("../data/demo-student.json", { cache: "no-store" }).then((r) => r.json());
    mount.innerHTML = render(view, student);
    document.querySelectorAll("[data-logout]").forEach((button) => button.addEventListener("click", () => { sessionStorage.removeItem("task-karate-demo-session"); location.href = "login.html"; }));
    document.querySelectorAll("[data-assignment]").forEach((input) => input.addEventListener("change", (event) => event.target.closest(".list-item")?.classList.toggle("is-complete", event.target.checked)));
  } catch (error) { mount.innerHTML = '<div class="portal-card"><h2>Portal data unavailable</h2><p>We could not load the demo profile. No private data has been stored.</p></div>'; console.error(error); }

  function render(currentView, data) {
    const views = { dashboard: dashboard, training: training, progress: progress, messages: messages, events: events, profile: profile };
    return (views[currentView] || dashboard)(data);
  }
  function dashboard(s) { return `<div class="portal-header"><div><span class="eyebrow">Student portal</span><h1>Hi, ${esc(s.name)}.</h1><p>Here is what matters for your training today.</p></div><button class="button button--outline button--small" data-logout type="button">Log out</button></div><div class="demo-notice" role="note"><strong>Demo mode.</strong> This profile is synthetic presentation data. It is not secure authentication and contains no real student record.</div><div class="portal-grid"><section class="portal-card"><header><h2>Your progress</h2><span class="badge">${esc(s.rank)}</span></header><div class="rank-row"><span class="belt-chip" aria-label="Green belt"></span><div><strong>${esc(s.nextRank)}</strong><div class="muted small">${s.classesSinceStripe} of ${s.classesToStripe} classes toward your next stripe</div></div></div><div class="progress-meter" role="progressbar" aria-label="Belt progress" aria-valuenow="${s.progress}" aria-valuemin="0" aria-valuemax="100"><span style="width:${s.progress}%"></span></div><div class="progress-meta"><span>${s.progress}% through this step</span><a href="progress.html">See your journey →</a></div></section><section class="portal-card"><header><h2>Next class</h2><span class="badge">Plan ahead</span></header><div class="next-class"><strong>${esc(s.nextClass.day)} · ${esc(s.nextClass.time)}</strong><span>${esc(s.nextClass.program)} · ${esc(s.nextClass.group)}</span></div><a class="button button--outline button--small" href="../schedule.html">View full schedule</a></section><section class="portal-card"><header><h2>Practice prompts</h2><a href="training.html">Training →</a></header><ul class="list">${s.assignments.map((a) => `<li class="list-item"><input data-assignment type="checkbox" aria-label="Mark ${esc(a.title)} complete" ${a.done ? "checked" : ""}><div><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div><span class="badge">${esc(a.due)}</span></li>`).join("")}</ul></section><section class="portal-card"><header><h2>Messages</h2><a href="messages.html">Open all →</a></header><ul class="list">${s.messages.map((m) => `<li class="list-item"><span class="badge ${m.unread ? "badge--gold" : ""}">${m.unread ? "New" : "Read"}</span><div><strong>${esc(m.from)}</strong><small>${esc(m.text)}</small></div><small>${esc(m.date)}</small></li>`).join("")}</ul></section><section class="portal-card portal-card--wide"><header><h2>Recent wins</h2><a href="progress.html">Progress →</a></header><div class="grid grid--3">${s.achievements.map((a) => `<div class="paper-panel stat"><strong>${esc(a.title)}</strong><span>${esc(a.category)} · ${esc(a.tier)} · ${esc(a.progress)}</span></div>`).join("")}</div></section></div>`; }
  function training(s) { return `<div class="portal-header"><div><span class="eyebrow">Training</span><h1>Keep the work moving.</h1><p>Your next class, practice prompts, and recent attendance in one place.</p></div><a class="button button--outline button--small" href="index.html">Dashboard</a></div><div class="portal-grid"><section class="portal-card"><header><h2>Next class</h2><span class="badge">${esc(s.nextClass.day)}</span></header><div class="next-class"><strong>${esc(s.nextClass.time)} · ${esc(s.nextClass.program)}</strong><span>${esc(s.nextClass.group)}</span></div><a class="button" href="../schedule.html">Open public schedule</a></section><section class="portal-card"><header><h2>Attendance</h2></header><p><strong>${s.totalClasses}</strong> total classes recorded in this demo profile.</p><ul class="list">${s.attendance.map((date) => `<li class="list-item"><span class="badge">✓</span><div><strong>Training session</strong><small>Checked in and ready to learn</small></div><small>${esc(date)}</small></li>`).join("")}</ul></section><section class="portal-card portal-card--wide"><header><h2>Practice prompts</h2><span class="badge">Instructor-led</span></header><ul class="list">${s.assignments.map((a) => `<li class="list-item"><input data-assignment type="checkbox" aria-label="Mark ${esc(a.title)} complete"><div><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div><span class="badge">${esc(a.due)}</span></li>`).join("")}</ul><p class="small muted">Assignments are reminders, not a substitute for instructor guidance.</p></section></div>`; }
  function progress(s) { return `<div class="portal-header"><div><span class="eyebrow">Journey &amp; progress</span><h1>See the steps adding up.</h1><p>Progress is more than a color—it is the habits you build along the way.</p></div><a class="button button--outline button--small" href="index.html">Dashboard</a></div><div class="portal-grid"><section class="portal-card"><header><h2>${esc(s.rank)}</h2><span class="badge">${s.progress}%</span></header><div class="rank-row"><span class="belt-chip" aria-label="Green belt"></span><div><strong>${esc(s.nextRank)}</strong><div class="muted small">${s.classesSinceStripe} of ${s.classesToStripe} classes toward next stripe</div></div></div><div class="progress-meter" role="progressbar" aria-label="Belt progress" aria-valuenow="${s.progress}" aria-valuemin="0" aria-valuemax="100"><span style="width:${s.progress}%"></span></div></section><section class="portal-card"><header><h2>Achievements</h2><span class="badge badge--gold">${s.achievements.length} tracked</span></header><ul class="list">${s.achievements.map((a) => `<li class="list-item"><span class="badge badge--gold">★</span><div><strong>${esc(a.title)}</strong><small>${esc(a.category)} · ${esc(a.tier)}</small></div><small>${esc(a.progress)}</small></li>`).join("")}</ul></section><section class="portal-card portal-card--wide"><header><h2>Training timeline</h2><span class="muted small">Recent attendance</span></header><div class="timeline">${s.attendance.map((date, i) => `<div class="timeline-item"><div class="timeline-date">${esc(date)}</div><div class="timeline-content"><strong>${i === 0 ? "Most recent class" : "Training session"}</strong><p class="muted small">Keep noticing what changed, what challenged you, and what you want to practice next.</p></div></div>`).join("")}</div></section></div>`; }
  function messages(s) { return `<div class="portal-header"><div><span class="eyebrow">Messages</span><h1>Keep communication clear.</h1><p>Instructor and training-partner messages belong here—not in a public feed.</p></div><a class="button button--outline button--small" href="index.html">Dashboard</a></div><div class="portal-grid"><section class="portal-card portal-card--wide"><header><h2>Your conversations</h2><span class="badge">${s.messages.filter((m) => m.unread).length} unread</span></header><ul class="list">${s.messages.map((m) => `<li class="list-item"><span class="badge ${m.unread ? "badge--gold" : ""}">${m.unread ? "New" : "Read"}</span><div><strong>${esc(m.from)} <span class="muted">· ${esc(m.role)}</span></strong><small>${esc(m.text)}</small></div><small>${esc(m.date)}</small></li>`).join("")}</ul><p class="small muted">Production boundary: a real portal must enforce student/guardian/instructor permissions on the server and protect message history.</p></section></div>`; }
  function events(s) { return `<div class="portal-header"><div><span class="eyebrow">Events</span><h1>Know what is coming up.</h1><p>Testing, seminars, and school events are easier to act on when they are in one place.</p></div><a class="button button--outline button--small" href="index.html">Dashboard</a></div><div class="portal-grid"><section class="portal-card portal-card--wide"><header><h2>Upcoming information</h2><span class="badge">School updates</span></header><ul class="list">${s.events.map((event) => `<li class="list-item"><span class="badge badge--gold">${esc(event.date)}</span><div><strong>${esc(event.title)}</strong><small>${esc(event.detail)}</small></div></li>`).join("")}</ul><a href="../news.html">Check public updates →</a></section></div>`; }
  function profile(s) { return `<div class="portal-header"><div><span class="eyebrow">Profile</span><h1>${esc(s.fullName)}</h1><p>Your training summary and demo session controls.</p></div><button class="button button--outline button--small" data-logout type="button">Log out</button></div><div class="portal-grid"><section class="portal-card"><header><h2>Training summary</h2><span class="badge">${esc(s.rank)}</span></header><ul class="list"><li class="list-item"><div><strong>Total classes</strong><small>Recorded in this demo profile</small></div><strong>${s.totalClasses}</strong></li><li class="list-item"><div><strong>Current step</strong><small>Next progression milestone</small></div><strong>${esc(s.nextRank)}</strong></li></ul></section><section class="portal-card"><header><h2>Demo session</h2></header><p class="muted">This logout clears the local demo session only. It does not revoke a real account because no real account is connected.</p><button class="button" data-logout type="button">Log out of demo</button></section></div>`; }
  function esc(value) { return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
})();
