<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  type Template = { templateId: number; name: string; dayOfWeek: string; startTime: string; durationMinutes: number; beltScope?: string; classType?: string; appointmentOnly?: boolean; programId: number };
  type Program = { programId: number; name: string; description?: string; templates: Template[] };
  type Session = { sessionId: number; classTemplateId: number; name: string; startTime: string; durationMinutes: number; sessionDateUtc: string; isCancelled: boolean; classType: string; assignedStudentId?: number; location?: string };
  type Student = { studentId: number; displayName: string; status: 'active' | 'paused' | 'deactivated' };
  type Enrollment = { enrollmentId: number; studentId: number; studentName: string; classTemplateId: number; className: string; isActive: boolean };
  let programs: Program[] = []; let sessions: Session[] = []; let templates: Template[] = []; let enrollments: Enrollment[] = []; let portalStudents: Student[] = [];
  let selectedDate = new Date().toISOString().slice(0, 10); let error = ''; let notice = ''; let loading = true; let programName = '';
  let template = { programId: '', name: '', dayOfWeek: 'Monday', startTime: '05:00 PM', durationMinutes: 60, beltScope: '', classType: 'Class', appointmentOnly: false };
  let session = { classTemplateId: '', sessionDateUtc: selectedDate, notes: '', assignedStudentId: '' };
  let enrollment = { studentId: '', classTemplateId: '' };
  async function load() { loading = true; error = ''; try { [programs, sessions, enrollments, portalStudents] = await Promise.all([api<Program[]>('/api/portal-admin/programs'), api<Session[]>(`/api/portal-admin/sessions?date=${selectedDate}`), api<Enrollment[]>('/api/portal-admin/enrollments'), api<Student[]>('/api/portal-admin/students')]); templates = programs.flatMap((item) => item.templates); session = { ...session, sessionDateUtc: selectedDate }; } catch (e) { error = e instanceof Error ? e.message : 'Could not load class data.'; } finally { loading = false; } }
  async function createProgram() { try { await api('/api/portal-admin/programs', { method: 'POST', body: JSON.stringify({ name: programName, description: 'Managed in the Task Karate staff workspace.' }) }); programName = ''; notice = 'Program created in the canonical portal database.'; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not create program.'; } }
  async function createTemplate() { try { await api('/api/portal-admin/class-templates', { method: 'POST', body: JSON.stringify({ ...template, programId: Number(template.programId), durationMinutes: Number(template.durationMinutes) }) }); notice = `${template.classType} template created in the canonical portal database.`; template = { ...template, name: '' }; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not create template.'; } }
  async function createSession() { try { await api('/api/portal-admin/sessions', { method: 'POST', body: JSON.stringify({ ...session, classTemplateId: Number(session.classTemplateId), assignedStudentId: session.assignedStudentId ? Number(session.assignedStudentId) : null, sessionDateUtc: new Date(`${selectedDate}T00:00:00Z`).toISOString() }) }); notice = `Session created for ${new Date(`${selectedDate}T12:00:00`).toLocaleDateString()}.`; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not create session.'; } }
  async function addEnrollment() { try { await api('/api/portal-admin/enrollments', { method: 'POST', body: JSON.stringify({ studentId: Number(enrollment.studentId), classTemplateId: Number(enrollment.classTemplateId) }) }); notice = 'Student added to the recurring class roster.'; enrollment = { studentId: '', classTemplateId: '' }; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not add the enrollment.'; } }
  async function removeEnrollment(item: Enrollment) { if (!confirm(`Remove ${item.studentName} from ${item.className}?`)) return; try { await api(`/api/portal-admin/enrollments/${item.enrollmentId}`, { method: 'DELETE' }); notice = `${item.studentName} removed from the class roster.`; await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not remove the enrollment.'; } }
  $: eligibleStudents = portalStudents.filter((student) => student.status === 'active');
  $: selectedTemplate = templates.find((item) => item.templateId === Number(session.classTemplateId));
  onMount(load);
</script>
<svelte:head><title>Staff · Classes | Task Karate</title></svelte:head>
<div class="toolbar"><div><span class="eyebrow">CLASSES</span><h2>Programs and class sessions</h2><p class="muted">Templates describe recurring classes, special seminars, and appointment-only private lessons. Sessions are the dated occurrences students can attend.</p></div></div>
{#if error}<div class="error" role="alert">{error}</div>{/if}{#if notice}<div class="status" role="status">{notice}</div>{/if}
<section class="card date-toolbar"><label>Working date<input type="date" bind:value={selectedDate} on:change={load} /></label><span class="muted">{sessions.length} session{sessions.length === 1 ? '' : 's'} on this date</span></section>
<div class="split"><section class="card"><h3>Program</h3><form on:submit|preventDefault={createProgram} class="form-grid"><label class="full">Program name<input bind:value={programName} required placeholder="e.g. Kids Karate" /></label><div class="full"><button class="button" disabled={!programName.trim()}>Create program</button></div></form><h3>Class template</h3><form on:submit|preventDefault={createTemplate} class="form-grid"><label class="full">Program<select bind:value={template.programId} required><option value="" disabled>Select program</option>{#each programs as program}<option value={program.programId}>{program.name}</option>{/each}</select></label><label class="full">Template name<input bind:value={template.name} required placeholder="e.g. Glow-chuck seminar" /></label><label>Format<select bind:value={template.classType}><option>Class</option><option>Seminar</option><option>Private lesson</option></select></label><label>Day<select bind:value={template.dayOfWeek}>{#each ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as day}<option>{day}</option>{/each}</select></label><label>Start time<input bind:value={template.startTime} required /></label><label>Duration (minutes)<input type="number" min="1" max="480" bind:value={template.durationMinutes} required /></label><label>Belt scope<input bind:value={template.beltScope} placeholder="Optional" /></label><label class="check-row"><input type="checkbox" bind:checked={template.appointmentOnly} /> Appointment only</label><div class="full"><button class="button" disabled={!template.programId || !template.name.trim()}>Create template</button></div></form></section>
<section class="card"><h3>Create dated session</h3><form on:submit|preventDefault={createSession} class="form-grid"><label class="full">Template<select bind:value={session.classTemplateId} required><option value="" disabled>Select template</option>{#each templates as item}<option value={item.templateId}>{item.classType ?? 'Class'} · {item.name} · {item.startTime}</option>{/each}</select></label>{#if selectedTemplate?.classType === 'Private lesson'}<label class="full">Assign student<select bind:value={session.assignedStudentId} required><option value="" disabled>Select student</option>{#each eligibleStudents as student}<option value={student.studentId}>{student.displayName}</option>{/each}</select></label>{/if}<label class="full">Session date<input type="date" bind:value={selectedDate} required /></label><label class="full">Staff notes<textarea bind:value={session.notes} maxlength="500" rows="2" placeholder="Optional notes for the instructor team"></textarea></label><div class="full"><button class="button" disabled={!session.classTemplateId}>Create session</button></div></form><h3>Sessions on {new Date(`${selectedDate}T12:00:00`).toLocaleDateString()}</h3>{#if loading}<p class="muted">Loading sessions…</p>{:else}{#each sessions as item}<article class="announcement"><strong>{item.name}</strong><br /><span>{item.startTime} · {item.durationMinutes} minutes</span>{#if item.isCancelled}<span class="pill cancelled-pill">Cancelled</span>{/if}</article>{:else}<p class="muted">No sessions on this date.</p>{/each}{/if}</section></div>
<section class="card"><div class="section-heading"><div><span class="eyebrow">ROSTER CONTROL</span><h3>Recurring class enrollments</h3><p class="muted">Use this roster for students committed to a recurring class. Paused or deactivated portal students are not offered for new enrollment. Removing a student from a class does not erase attendance history.</p></div><span class="pill">{enrollments.length}</span></div><form class="form-grid" on:submit|preventDefault={addEnrollment}><label>Student<select bind:value={enrollment.studentId} required><option value="" disabled>Select student</option>{#each eligibleStudents as student}<option value={student.studentId}>{student.displayName}</option>{/each}</select></label><label>Recurring class<select bind:value={enrollment.classTemplateId} required><option value="" disabled>Select class</option>{#each templates as item}<option value={item.templateId}>{item.name} · {item.dayOfWeek} {item.startTime}</option>{/each}</select></label><div><button class="button" disabled={!enrollment.studentId || !enrollment.classTemplateId}>Add to roster</button></div></form><div class="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Action</th></tr></thead><tbody>{#each enrollments as item}<tr><td>{item.studentName}</td><td>{item.className}</td><td><button class="button danger small-button" type="button" on:click={() => removeEnrollment(item)}>Remove student from class</button></td></tr>{:else}<tr><td colspan="3" class="muted">No recurring enrollments have been added.</td></tr>{/each}</tbody></table></div></section>
